// Complete template specifications for 100 premium templates
// Distribution: Social Media (25), Business & Marketing (20), AI-Powered (15), 
// Real Estate (15), E-Commerce (10), Productivity (10), Professional Documents (5)

const SOCIAL_MEDIA_TEMPLATES = [
  // Instagram Posts (5)
  {
    id: 'instagram-posts-fitness',
    name: 'Instagram Posts Pack - Fitness & Wellness',
    category: 'social-media',
    subcategory: 'instagram-posts',
    priceCents: 2900,
    shortDescription: '20 high-engagement Instagram posts for fitness coaches and wellness brands.',
    fullDescription: 'Transform your fitness Instagram with 20 professionally crafted posts covering workout tips, nutrition advice, motivation, and client transformations. Each post includes caption, hashtags, and engagement prompts.',
    tags: ['instagram', 'fitness', 'wellness', 'social-media'],
    featured: true,
    whatsIncluded: ['20 ready-to-post captions', 'Hashtag sets for each post', 'Engagement prompts', 'Content calendar suggestions', 'Canva design tips'],
    whoItsFor: ['Fitness coaches', 'Personal trainers', 'Wellness brands', 'Gym owners']
  },
  {
    id: 'instagram-posts-coaching',
    name: 'Instagram Posts Pack - Life & Business Coaching',
    category: 'social-media',
    subcategory: 'instagram-posts',
    priceCents: 2900,
    shortDescription: '20 authority-building Instagram posts for coaches and consultants.',
    fullDescription: 'Establish yourself as a thought leader with 20 carefully crafted posts covering mindset, success strategies, client wins, and coaching insights. Perfect for life coaches, business coaches, and consultants.',
    tags: ['instagram', 'coaching', 'business', 'mindset'],
    featured: false,
    whatsIncluded: ['20 thought-leadership captions', 'Story prompts', 'Engagement questions', 'Hashtag research', 'Posting schedule'],
    whoItsFor: ['Life coaches', 'Business coaches', 'Consultants', 'Mentors']
  },
  {
    id: 'instagram-posts-ecommerce',
    name: 'Instagram Posts Pack - E-Commerce & Products',
    category: 'social-media',
    subcategory: 'instagram-posts',
    priceCents: 2900,
    shortDescription: '20 sales-driving Instagram posts for product-based businesses.',
    fullDescription: 'Drive sales and build brand loyalty with 20 product-focused posts including launch announcements, behind-the-scenes content, customer spotlights, and promotional campaigns.',
    tags: ['instagram', 'ecommerce', 'products', 'sales'],
    featured: false,
    whatsIncluded: ['20 product-focused captions', 'Launch announcement templates', 'Sale promotion posts', 'Customer spotlight formats', 'UGC request templates'],
    whoItsFor: ['E-commerce store owners', 'Product-based businesses', 'Shopify sellers', 'Handmade sellers']
  },
  {
    id: 'instagram-posts-restaurant',
    name: 'Instagram Posts Pack - Restaurants & Food',
    category: 'social-media',
    subcategory: 'instagram-posts',
    priceCents: 2900,
    shortDescription: '20 mouth-watering Instagram posts for restaurants and food businesses.',
    fullDescription: 'Make your followers hungry with 20 appetizing posts covering menu highlights, chef spotlights, behind-the-scenes kitchen content, and special promotions.',
    tags: ['instagram', 'restaurant', 'food', 'hospitality'],
    featured: false,
    whatsIncluded: ['20 food-focused captions', 'Menu highlight templates', 'Event promotion posts', 'Staff spotlight formats', 'Review request templates'],
    whoItsFor: ['Restaurant owners', 'Cafes', 'Food trucks', 'Catering businesses']
  },
  {
    id: 'instagram-posts-beauty',
    name: 'Instagram Posts Pack - Beauty & Skincare',
    category: 'social-media',
    subcategory: 'instagram-posts',
    priceCents: 2900,
    shortDescription: '20 stunning Instagram posts for beauty brands and skincare professionals.',
    fullDescription: 'Glow up your Instagram with 20 beauty-focused posts covering product education, skincare tips, before/after transformations, and trend content.',
    tags: ['instagram', 'beauty', 'skincare', 'cosmetics'],
    featured: false,
    whatsIncluded: ['20 beauty captions', 'Product education posts', 'Tutorial prompts', 'Trend content ideas', 'Influencer collaboration templates'],
    whoItsFor: ['Beauty brands', 'Estheticians', 'Makeup artists', 'Skincare professionals']
  },

  // TikTok Scripts (5)
  {
    id: 'tiktok-scripts-business',
    name: 'TikTok Script Pack - Business & Entrepreneurship',
    category: 'social-media',
    subcategory: 'tiktok-scripts',
    priceCents: 3400,
    shortDescription: '15 viral-ready TikTok scripts for entrepreneurs and business owners.',
    fullDescription: 'Go viral with 15 proven TikTok script formats covering business tips, entrepreneurship stories, money mindset, and success strategies. Each script includes hook, body, and CTA.',
    tags: ['tiktok', 'business', 'entrepreneur', 'viral'],
    featured: true,
    whatsIncluded: ['15 complete scripts', 'Hook formulas', 'Trending sound suggestions', 'Hashtag strategies', 'Posting time recommendations'],
    whoItsFor: ['Entrepreneurs', 'Business owners', 'Side hustlers', 'Startup founders']
  },
  {
    id: 'tiktok-scripts-education',
    name: 'TikTok Script Pack - Educational Content',
    category: 'social-media',
    subcategory: 'tiktok-scripts',
    priceCents: 3400,
    shortDescription: '15 engaging TikTok scripts for educators and course creators.',
    fullDescription: 'Educate and entertain with 15 TikTok scripts designed for teaching complex topics in simple, engaging ways. Perfect for course creators and educators.',
    tags: ['tiktok', 'education', 'teaching', 'courses'],
    featured: false,
    whatsIncluded: ['15 educational scripts', 'Explainer formats', 'Myth-busting templates', 'Quick tip structures', 'Series content ideas'],
    whoItsFor: ['Course creators', 'Teachers', 'Tutors', 'Subject matter experts']
  },
  {
    id: 'tiktok-scripts-lifestyle',
    name: 'TikTok Script Pack - Lifestyle & Vlogs',
    category: 'social-media',
    subcategory: 'tiktok-scripts',
    priceCents: 3400,
    shortDescription: '15 relatable TikTok scripts for lifestyle creators and vloggers.',
    fullDescription: 'Connect with your audience through 15 lifestyle-focused scripts covering day-in-the-life content, routines, hauls, and personal stories.',
    tags: ['tiktok', 'lifestyle', 'vlog', 'personal'],
    featured: false,
    whatsIncluded: ['15 lifestyle scripts', 'GRWM formats', 'Routine templates', 'Haul structures', 'Storytelling frameworks'],
    whoItsFor: ['Lifestyle creators', 'Vloggers', 'Influencers', 'Content creators']
  },
  {
    id: 'tiktok-scripts-comedy',
    name: 'TikTok Script Pack - Comedy & Entertainment',
    category: 'social-media',
    subcategory: 'tiktok-scripts',
    priceCents: 3400,
    shortDescription: '15 hilarious TikTok scripts for comedy creators.',
    fullDescription: 'Make your audience laugh with 15 comedy scripts covering relatable situations, parodies, character sketches, and trending formats.',
    tags: ['tiktok', 'comedy', 'entertainment', 'humor'],
    featured: false,
    whatsIncluded: ['15 comedy scripts', 'Sketch formats', 'Parody templates', 'Reaction structures', 'Duet ideas'],
    whoItsFor: ['Comedy creators', 'Entertainers', 'Sketch artists', 'Content creators']
  },
  {
    id: 'tiktok-scripts-health',
    name: 'TikTok Script Pack - Health & Fitness',
    category: 'social-media',
    subcategory: 'tiktok-scripts',
    priceCents: 3400,
    shortDescription: '15 motivating TikTok scripts for health and fitness creators.',
    fullDescription: 'Inspire your audience with 15 health and fitness scripts covering workout tips, nutrition facts, transformation stories, and motivation.',
    tags: ['tiktok', 'health', 'fitness', 'wellness'],
    featured: false,
    whatsIncluded: ['15 fitness scripts', 'Workout demo formats', 'Nutrition tip templates', 'Transformation structures', 'Challenge ideas'],
    whoItsFor: ['Fitness influencers', 'Personal trainers', 'Nutritionists', 'Wellness coaches']
  },

  // Reels Scripts (5)
  {
    id: 'reels-scripts-marketing',
    name: 'Instagram Reels Script Pack - Marketing Tips',
    category: 'social-media',
    subcategory: 'reels-scripts',
    priceCents: 2900,
    shortDescription: '15 scroll-stopping Reels scripts for marketing professionals.',
    fullDescription: 'Dominate the Reels algorithm with 15 marketing-focused scripts covering social media tips, content strategies, and growth hacks.',
    tags: ['reels', 'marketing', 'social-media', 'growth'],
    featured: true,
    whatsIncluded: ['15 marketing scripts', 'Hook formulas', 'Trend adaptations', 'Audio suggestions', 'Caption templates'],
    whoItsFor: ['Marketing professionals', 'Social media managers', 'Agency owners', 'Brand managers']
  },
  {
    id: 'reels-scripts-real-estate',
    name: 'Instagram Reels Script Pack - Real Estate',
    category: 'social-media',
    subcategory: 'reels-scripts',
    priceCents: 2900,
    shortDescription: '15 property-showcasing Reels scripts for real estate agents.',
    fullDescription: 'Sell more properties with 15 real estate Reels scripts covering property tours, market updates, buyer tips, and agent life content.',
    tags: ['reels', 'real-estate', 'property', 'agent'],
    featured: false,
    whatsIncluded: ['15 real estate scripts', 'Property tour formats', 'Market update templates', 'Client testimonial structures', 'Day-in-the-life formats'],
    whoItsFor: ['Real estate agents', 'Brokers', 'Property managers', 'Real estate teams']
  },
  {
    id: 'reels-scripts-food',
    name: 'Instagram Reels Script Pack - Food & Recipe',
    category: 'social-media',
    subcategory: 'reels-scripts',
    priceCents: 2900,
    shortDescription: '15 delicious Reels scripts for food creators and restaurants.',
    fullDescription: 'Make mouths water with 15 food-focused Reels scripts covering recipe tutorials, restaurant features, and food reviews.',
    tags: ['reels', 'food', 'recipe', 'restaurant'],
    featured: false,
    whatsIncluded: ['15 food scripts', 'Recipe formats', 'Review templates', 'Behind-the-scenes structures', 'Trending food content ideas'],
    whoItsFor: ['Food bloggers', 'Restaurants', 'Chefs', 'Recipe creators']
  },
  {
    id: 'reels-scripts-fashion',
    name: 'Instagram Reels Script Pack - Fashion & Style',
    category: 'social-media',
    subcategory: 'reels-scripts',
    priceCents: 2900,
    shortDescription: '15 trendy Reels scripts for fashion influencers and brands.',
    fullDescription: 'Stay on trend with 15 fashion Reels scripts covering outfit ideas, styling tips, hauls, and trend reports.',
    tags: ['reels', 'fashion', 'style', 'trends'],
    featured: false,
    whatsIncluded: ['15 fashion scripts', 'OOTD formats', 'Haul templates', 'Styling tip structures', 'Trend report formats'],
    whoItsFor: ['Fashion influencers', 'Stylists', 'Boutique owners', 'Fashion brands']
  },
  {
    id: 'reels-scripts-travel',
    name: 'Instagram Reels Script Pack - Travel & Adventure',
    category: 'social-media',
    subcategory: 'reels-scripts',
    priceCents: 2900,
    shortDescription: '15 wanderlust-inducing Reels scripts for travel creators.',
    fullDescription: 'Inspire wanderlust with 15 travel Reels scripts covering destination guides, travel tips, hotel reviews, and adventure content.',
    tags: ['reels', 'travel', 'adventure', 'destination'],
    featured: false,
    whatsIncluded: ['15 travel scripts', 'Destination guide formats', 'Travel tip templates', 'Hotel review structures', 'Packing content ideas'],
    whoItsFor: ['Travel influencers', 'Travel bloggers', 'Tourism businesses', 'Adventure creators']
  },

  // Carousel Templates (5)
  {
    id: 'carousel-educational',
    name: 'Instagram Carousel Pack - Educational Content',
    category: 'social-media',
    subcategory: 'carousel-templates',
    priceCents: 3400,
    shortDescription: '10 high-save carousel templates for educational content.',
    fullDescription: 'Create save-worthy educational carousels with 10 templates covering how-to guides, listicles, myth-busting, and step-by-step tutorials.',
    tags: ['carousel', 'educational', 'instagram', 'infographic'],
    featured: true,
    whatsIncluded: ['10 carousel structures', 'Slide-by-slide breakdowns', 'Design tips', 'Caption templates', 'CTA suggestions'],
    whoItsFor: ['Educators', 'Course creators', 'Coaches', 'Subject matter experts']
  },
  {
    id: 'carousel-storytelling',
    name: 'Instagram Carousel Pack - Storytelling',
    category: 'social-media',
    subcategory: 'carousel-templates',
    priceCents: 3400,
    shortDescription: '10 engaging carousel templates for brand storytelling.',
    fullDescription: 'Tell compelling stories with 10 carousel templates covering brand origin stories, customer journeys, case studies, and transformation narratives.',
    tags: ['carousel', 'storytelling', 'brand', 'narrative'],
    featured: false,
    whatsIncluded: ['10 storytelling structures', 'Narrative frameworks', 'Visual flow guides', 'Emotional hooks', 'Engagement prompts'],
    whoItsFor: ['Brand owners', 'Marketers', 'Storytellers', 'Content creators']
  },
  {
    id: 'carousel-tips-tricks',
    name: 'Instagram Carousel Pack - Tips & Tricks',
    category: 'social-media',
    subcategory: 'carousel-templates',
    priceCents: 3400,
    shortDescription: '10 shareable carousel templates for tips and hacks content.',
    fullDescription: 'Get shared and saved with 10 carousel templates designed for tips, tricks, hacks, and quick-win content that audiences love to share.',
    tags: ['carousel', 'tips', 'hacks', 'shareable'],
    featured: false,
    whatsIncluded: ['10 tips formats', 'Numbered list structures', 'Before/after layouts', 'Comparison templates', 'Quick-win frameworks'],
    whoItsFor: ['Influencers', 'Experts', 'Coaches', 'Content creators']
  },
  {
    id: 'carousel-product',
    name: 'Instagram Carousel Pack - Product Showcase',
    category: 'social-media',
    subcategory: 'carousel-templates',
    priceCents: 3400,
    shortDescription: '10 sales-driving carousel templates for product launches.',
    fullDescription: 'Launch products effectively with 10 carousel templates covering product features, benefits, comparisons, and customer testimonials.',
    tags: ['carousel', 'product', 'launch', 'sales'],
    featured: false,
    whatsIncluded: ['10 product showcase formats', 'Feature highlight structures', 'Benefit breakdowns', 'Comparison layouts', 'Testimonial integrations'],
    whoItsFor: ['E-commerce brands', 'Product creators', 'Shopify sellers', 'DTC brands']
  },
  {
    id: 'carousel-personal-brand',
    name: 'Instagram Carousel Pack - Personal Branding',
    category: 'social-media',
    subcategory: 'carousel-templates',
    priceCents: 3400,
    shortDescription: '10 authority-building carousel templates for personal brands.',
    fullDescription: 'Build your personal brand with 10 carousel templates covering your story, expertise, values, and unique perspective.',
    tags: ['carousel', 'personal-brand', 'authority', 'thought-leadership'],
    featured: false,
    whatsIncluded: ['10 personal brand formats', 'About me structures', 'Expertise showcases', 'Value proposition layouts', 'Journey narratives'],
    whoItsFor: ['Entrepreneurs', 'Coaches', 'Consultants', 'Thought leaders']
  },

  // YouTube Shorts Scripts (5)
  {
    id: 'youtube-shorts-tech',
    name: 'YouTube Shorts Script Pack - Tech & Gadgets',
    category: 'social-media',
    subcategory: 'youtube-shorts',
    priceCents: 3400,
    shortDescription: '15 engaging YouTube Shorts scripts for tech reviewers.',
    fullDescription: 'Create viral tech content with 15 YouTube Shorts scripts covering gadget reviews, tech tips, app recommendations, and unboxings.',
    tags: ['youtube-shorts', 'tech', 'gadgets', 'reviews'],
    featured: true,
    whatsIncluded: ['15 tech scripts', 'Review formats', 'Comparison structures', 'Unboxing templates', 'Quick tip formats'],
    whoItsFor: ['Tech reviewers', 'Gadget enthusiasts', 'App reviewers', 'Tech educators']
  },
  {
    id: 'youtube-shorts-finance',
    name: 'YouTube Shorts Script Pack - Personal Finance',
    category: 'social-media',
    subcategory: 'youtube-shorts',
    priceCents: 3400,
    shortDescription: '15 educational YouTube Shorts scripts for finance creators.',
    fullDescription: 'Educate your audience about money with 15 finance Shorts scripts covering budgeting, investing, saving tips, and money mindset.',
    tags: ['youtube-shorts', 'finance', 'money', 'investing'],
    featured: false,
    whatsIncluded: ['15 finance scripts', 'Money tip formats', 'Investment explainers', 'Budget breakdowns', 'Myth-busting structures'],
    whoItsFor: ['Finance educators', 'Financial advisors', 'Money coaches', 'Investment creators']
  },
  {
    id: 'youtube-shorts-diy',
    name: 'YouTube Shorts Script Pack - DIY & Crafts',
    category: 'social-media',
    subcategory: 'youtube-shorts',
    priceCents: 3400,
    shortDescription: '15 creative YouTube Shorts scripts for DIY and craft creators.',
    fullDescription: 'Inspire creativity with 15 DIY Shorts scripts covering craft tutorials, home projects, upcycling ideas, and creative hacks.',
    tags: ['youtube-shorts', 'diy', 'crafts', 'creative'],
    featured: false,
    whatsIncluded: ['15 DIY scripts', 'Tutorial formats', 'Before/after structures', 'Supply list templates', 'Time-lapse guides'],
    whoItsFor: ['DIY creators', 'Craft bloggers', 'Home improvement enthusiasts', 'Creative makers']
  },
  {
    id: 'youtube-shorts-gaming',
    name: 'YouTube Shorts Script Pack - Gaming',
    category: 'social-media',
    subcategory: 'youtube-shorts',
    priceCents: 3400,
    shortDescription: '15 entertaining YouTube Shorts scripts for gaming creators.',
    fullDescription: 'Level up your gaming content with 15 Shorts scripts covering gameplay highlights, tips and tricks, game reviews, and gaming humor.',
    tags: ['youtube-shorts', 'gaming', 'esports', 'gameplay'],
    featured: false,
    whatsIncluded: ['15 gaming scripts', 'Highlight formats', 'Tips structures', 'Review templates', 'Reaction formats'],
    whoItsFor: ['Gaming creators', 'Streamers', 'Esports enthusiasts', 'Game reviewers']
  },
  {
    id: 'youtube-shorts-motivation',
    name: 'YouTube Shorts Script Pack - Motivation & Success',
    category: 'social-media',
    subcategory: 'youtube-shorts',
    priceCents: 3400,
    shortDescription: '15 inspiring YouTube Shorts scripts for motivational content.',
    fullDescription: 'Inspire millions with 15 motivational Shorts scripts covering success stories, mindset shifts, productivity tips, and life lessons.',
    tags: ['youtube-shorts', 'motivation', 'success', 'mindset'],
    featured: false,
    whatsIncluded: ['15 motivation scripts', 'Story formats', 'Quote structures', 'Lesson templates', 'Challenge formats'],
    whoItsFor: ['Motivational speakers', 'Life coaches', 'Success mentors', 'Personal development creators']
  }
];

const BUSINESS_MARKETING_TEMPLATES = [
  // Business Plans (5)
  {
    id: 'business-plan-startup',
    name: 'Startup Business Plan Template',
    category: 'business-marketing',
    subcategory: 'business-plans',
    priceCents: 4900,
    shortDescription: 'Complete 10-page business plan template for tech startups.',
    fullDescription: 'Launch your startup with confidence using this comprehensive business plan template. Includes executive summary, market analysis, financial projections, and investor-ready formatting.',
    tags: ['business-plan', 'startup', 'investor', 'funding'],
    featured: true,
    whatsIncluded: ['10-page template', 'Financial projection spreadsheets', 'Market analysis framework', 'Pitch deck outline', 'Investor checklist'],
    whoItsFor: ['Startup founders', 'Tech entrepreneurs', 'First-time founders', 'Seeking funding']
  },
  {
    id: 'business-plan-ecommerce',
    name: 'E-Commerce Business Plan Template',
    category: 'business-marketing',
    subcategory: 'business-plans',
    priceCents: 4900,
    shortDescription: 'Detailed business plan template for online stores and DTC brands.',
    fullDescription: 'Plan your e-commerce empire with this specialized template covering product sourcing, fulfillment strategy, marketing channels, and growth projections.',
    tags: ['business-plan', 'ecommerce', 'online-store', 'dtc'],
    featured: false,
    whatsIncluded: ['8-page template', 'Product margin calculator', 'Marketing budget planner', 'Fulfillment cost analysis', 'Growth projections'],
    whoItsFor: ['E-commerce entrepreneurs', 'Shopify store owners', 'DTC brand founders', 'Online retailers']
  },
  {
    id: 'business-plan-service',
    name: 'Service Business Plan Template',
    category: 'business-marketing',
    subcategory: 'business-plans',
    priceCents: 4900,
    shortDescription: 'Professional business plan template for service-based businesses.',
    fullDescription: 'Structure your service business with this template covering service offerings, pricing strategy, client acquisition, and operational planning.',
    tags: ['business-plan', 'service', 'consulting', 'agency'],
    featured: false,
    whatsIncluded: ['8-page template', 'Service pricing calculator', 'Client acquisition funnel', 'Capacity planning tool', 'Revenue projections'],
    whoItsFor: ['Consultants', 'Agency owners', 'Freelancers scaling up', 'Service providers']
  },
  {
    id: 'business-plan-restaurant',
    name: 'Restaurant Business Plan Template',
    category: 'business-marketing',
    subcategory: 'business-plans',
    priceCents: 4900,
    shortDescription: 'Comprehensive business plan template for restaurants and food businesses.',
    fullDescription: 'Open your dream restaurant with this detailed template covering concept development, menu planning, location analysis, and financial projections.',
    tags: ['business-plan', 'restaurant', 'food', 'hospitality'],
    featured: false,
    whatsIncluded: ['10-page template', 'Menu costing spreadsheet', 'Location analysis checklist', 'Staffing plan', 'Break-even calculator'],
    whoItsFor: ['Restaurant owners', 'Food entrepreneurs', 'Cafe owners', 'Food truck operators']
  },
  {
    id: 'business-plan-coaching',
    name: 'Coaching Business Plan Template',
    category: 'business-marketing',
    subcategory: 'business-plans',
    priceCents: 4900,
    shortDescription: 'Strategic business plan template for coaches and consultants.',
    fullDescription: 'Build a thriving coaching practice with this template covering niche selection, program development, pricing tiers, and client acquisition strategy.',
    tags: ['business-plan', 'coaching', 'consulting', 'online-business'],
    featured: false,
    whatsIncluded: ['8-page template', 'Program pricing matrix', 'Client journey map', 'Launch timeline', 'Revenue model'],
    whoItsFor: ['Life coaches', 'Business coaches', 'Consultants', 'Online course creators']
  },

  // Branding Kits (5)
  {
    id: 'branding-kit-startup',
    name: 'Startup Branding Kit',
    category: 'business-marketing',
    subcategory: 'branding-kits',
    priceCents: 3900,
    shortDescription: 'Complete brand identity kit for tech startups and SaaS companies.',
    fullDescription: 'Build a memorable brand with this comprehensive kit including brand voice guidelines, color psychology, typography recommendations, and messaging frameworks.',
    tags: ['branding', 'startup', 'identity', 'guidelines'],
    featured: true,
    whatsIncluded: ['Brand voice guide', 'Color palette templates', 'Typography guidelines', 'Logo usage rules', 'Messaging framework'],
    whoItsFor: ['Startup founders', 'SaaS companies', 'Tech brands', 'New businesses']
  },
  {
    id: 'branding-kit-personal',
    name: 'Personal Brand Kit',
    category: 'business-marketing',
    subcategory: 'branding-kits',
    priceCents: 3900,
    shortDescription: 'Build your personal brand with this comprehensive identity kit.',
    fullDescription: 'Stand out as a thought leader with this personal branding kit covering your unique value proposition, visual identity, and content pillars.',
    tags: ['branding', 'personal-brand', 'thought-leader', 'identity'],
    featured: false,
    whatsIncluded: ['Personal brand workbook', 'Visual identity guide', 'Content pillar framework', 'Bio templates', 'Social media guidelines'],
    whoItsFor: ['Entrepreneurs', 'Coaches', 'Consultants', 'Influencers']
  },
  {
    id: 'branding-kit-ecommerce',
    name: 'E-Commerce Branding Kit',
    category: 'business-marketing',
    subcategory: 'branding-kits',
    priceCents: 3900,
    shortDescription: 'Product-focused branding kit for online stores and DTC brands.',
    fullDescription: 'Create a cohesive brand experience with this e-commerce focused kit covering product photography guidelines, packaging design, and customer touchpoints.',
    tags: ['branding', 'ecommerce', 'product', 'packaging'],
    featured: false,
    whatsIncluded: ['Brand guidelines', 'Product photography tips', 'Packaging design guide', 'Email design templates', 'Social media style guide'],
    whoItsFor: ['E-commerce brands', 'Product sellers', 'DTC companies', 'Shopify stores']
  },
  {
    id: 'branding-kit-wellness',
    name: 'Wellness Brand Kit',
    category: 'business-marketing',
    subcategory: 'branding-kits',
    priceCents: 3900,
    shortDescription: 'Calming and professional branding kit for wellness businesses.',
    fullDescription: 'Create a serene brand presence with this wellness-focused kit including calming color palettes, mindful messaging, and holistic brand guidelines.',
    tags: ['branding', 'wellness', 'health', 'spa'],
    featured: false,
    whatsIncluded: ['Wellness brand guide', 'Calming color palettes', 'Mindful messaging templates', 'Photography style guide', 'Client experience map'],
    whoItsFor: ['Wellness coaches', 'Yoga studios', 'Spas', 'Health practitioners']
  },
  {
    id: 'branding-kit-luxury',
    name: 'Luxury Brand Kit',
    category: 'business-marketing',
    subcategory: 'branding-kits',
    priceCents: 3900,
    shortDescription: 'Premium branding kit for luxury and high-end businesses.',
    fullDescription: 'Position your brand as premium with this luxury-focused kit covering sophisticated aesthetics, exclusive messaging, and high-end customer experience.',
    tags: ['branding', 'luxury', 'premium', 'high-end'],
    featured: false,
    whatsIncluded: ['Luxury brand guidelines', 'Premium color palettes', 'Sophisticated typography', 'Exclusive messaging framework', 'VIP experience guide'],
    whoItsFor: ['Luxury brands', 'High-end services', 'Premium products', 'Exclusive experiences']
  },

  // Email Sequences (5)
  {
    id: 'email-sequence-welcome',
    name: 'Welcome Email Sequence (12 Emails)',
    category: 'business-marketing',
    subcategory: 'email-sequences',
    priceCents: 3900,
    shortDescription: '12-email welcome sequence that converts subscribers to customers.',
    fullDescription: 'Turn new subscribers into loyal customers with this proven 12-email welcome sequence covering introduction, value delivery, and conversion.',
    tags: ['email', 'welcome', 'sequence', 'conversion'],
    featured: true,
    whatsIncluded: ['12 email templates', 'Subject line formulas', 'Send timing guide', 'Segmentation strategy', 'A/B testing tips'],
    whoItsFor: ['Email marketers', 'Course creators', 'E-commerce brands', 'Newsletter writers']
  },
  {
    id: 'email-sequence-launch',
    name: 'Product Launch Email Sequence (15 Emails)',
    category: 'business-marketing',
    subcategory: 'email-sequences',
    priceCents: 4400,
    shortDescription: '15-email launch sequence for maximum product sales.',
    fullDescription: 'Launch your product with impact using this 15-email sequence covering pre-launch buzz, cart open, and urgency-driven close.',
    tags: ['email', 'launch', 'product', 'sales'],
    featured: false,
    whatsIncluded: ['15 launch emails', 'Pre-launch sequence', 'Cart open emails', 'Urgency templates', 'Post-launch follow-up'],
    whoItsFor: ['Course creators', 'Product launchers', 'SaaS companies', 'E-commerce brands']
  },
  {
    id: 'email-sequence-nurture',
    name: 'Lead Nurture Email Sequence (20 Emails)',
    category: 'business-marketing',
    subcategory: 'email-sequences',
    priceCents: 4400,
    shortDescription: '20-email nurture sequence that builds trust and drives sales.',
    fullDescription: 'Nurture leads into customers with this comprehensive 20-email sequence covering education, trust-building, and soft selling.',
    tags: ['email', 'nurture', 'leads', 'trust'],
    featured: false,
    whatsIncluded: ['20 nurture emails', 'Content themes', 'Story frameworks', 'Soft sell templates', 'Re-engagement emails'],
    whoItsFor: ['B2B companies', 'Service providers', 'Coaches', 'Consultants']
  },
  {
    id: 'email-sequence-abandoned-cart',
    name: 'Abandoned Cart Email Sequence (5 Emails)',
    category: 'business-marketing',
    subcategory: 'email-sequences',
    priceCents: 2900,
    shortDescription: '5-email abandoned cart sequence that recovers lost sales.',
    fullDescription: 'Recover abandoned carts with this proven 5-email sequence covering reminder, incentive, urgency, and last chance messaging.',
    tags: ['email', 'abandoned-cart', 'ecommerce', 'recovery'],
    featured: false,
    whatsIncluded: ['5 recovery emails', 'Timing strategy', 'Discount frameworks', 'Urgency templates', 'Win-back tactics'],
    whoItsFor: ['E-commerce stores', 'Shopify sellers', 'Online retailers', 'DTC brands']
  },
  {
    id: 'email-sequence-webinar',
    name: 'Webinar Email Sequence (12 Emails)',
    category: 'business-marketing',
    subcategory: 'email-sequences',
    priceCents: 3900,
    shortDescription: '12-email webinar sequence from registration to replay.',
    fullDescription: 'Fill your webinars and convert attendees with this 12-email sequence covering registration, reminders, and post-webinar sales.',
    tags: ['email', 'webinar', 'registration', 'conversion'],
    featured: false,
    whatsIncluded: ['12 webinar emails', 'Registration sequence', 'Reminder templates', 'Show-up boosters', 'Replay sequence'],
    whoItsFor: ['Webinar hosts', 'Course creators', 'Coaches', 'B2B marketers']
  },

  // Sales Funnels (5)
  {
    id: 'sales-funnel-webinar',
    name: 'Webinar Sales Funnel Framework',
    category: 'business-marketing',
    subcategory: 'sales-funnels',
    priceCents: 4900,
    shortDescription: 'Complete webinar funnel framework with 7 stages.',
    fullDescription: 'Build a high-converting webinar funnel with this comprehensive framework covering registration, attendance, pitch, and follow-up.',
    tags: ['funnel', 'webinar', 'sales', 'conversion'],
    featured: true,
    whatsIncluded: ['7-stage funnel map', 'Landing page copy', 'Email sequences', 'Webinar script outline', 'Follow-up strategy'],
    whoItsFor: ['Course creators', 'Coaches', 'Consultants', 'Info product sellers']
  },
  {
    id: 'sales-funnel-tripwire',
    name: 'Tripwire Sales Funnel Framework',
    category: 'business-marketing',
    subcategory: 'sales-funnels',
    priceCents: 3900,
    shortDescription: 'Low-ticket to high-ticket tripwire funnel framework.',
    fullDescription: 'Convert leads with a low-ticket offer and ascend them to premium products using this proven tripwire funnel framework.',
    tags: ['funnel', 'tripwire', 'low-ticket', 'ascension'],
    featured: false,
    whatsIncluded: ['5-stage funnel map', 'Tripwire offer framework', 'Upsell sequences', 'Order bump ideas', 'Backend offers'],
    whoItsFor: ['Digital product sellers', 'Course creators', 'E-commerce brands', 'Info marketers']
  },
  {
    id: 'sales-funnel-challenge',
    name: 'Challenge Funnel Framework',
    category: 'business-marketing',
    subcategory: 'sales-funnels',
    priceCents: 4900,
    shortDescription: '5-day challenge funnel that builds community and converts.',
    fullDescription: 'Launch a profitable challenge with this framework covering daily content, engagement strategies, and conversion events.',
    tags: ['funnel', 'challenge', 'community', 'launch'],
    featured: false,
    whatsIncluded: ['Challenge structure', 'Daily content outlines', 'Email sequences', 'Facebook group strategy', 'Conversion event script'],
    whoItsFor: ['Coaches', 'Course creators', 'Community builders', 'Membership owners']
  },
  {
    id: 'sales-funnel-vsl',
    name: 'VSL Sales Funnel Framework',
    category: 'business-marketing',
    subcategory: 'sales-funnels',
    priceCents: 4900,
    shortDescription: 'Video sales letter funnel framework for high-ticket offers.',
    fullDescription: 'Sell high-ticket offers with this VSL funnel framework covering video script structure, landing page elements, and follow-up sequences.',
    tags: ['funnel', 'vsl', 'video', 'high-ticket'],
    featured: false,
    whatsIncluded: ['VSL script framework', 'Landing page structure', 'Objection handling', 'Follow-up sequences', 'Retargeting strategy'],
    whoItsFor: ['High-ticket sellers', 'Course creators', 'Coaches', 'Agency owners']
  },
  {
    id: 'sales-funnel-lead-magnet',
    name: 'Lead Magnet Funnel Framework',
    category: 'business-marketing',
    subcategory: 'sales-funnels',
    priceCents: 2900,
    shortDescription: 'Simple lead magnet funnel that builds your email list.',
    fullDescription: 'Grow your email list with this straightforward lead magnet funnel covering opt-in page, delivery, and nurture sequence.',
    tags: ['funnel', 'lead-magnet', 'email-list', 'opt-in'],
    featured: false,
    whatsIncluded: ['Funnel map', 'Opt-in page copy', 'Thank you page', 'Delivery email', 'Nurture sequence'],
    whoItsFor: ['List builders', 'Content creators', 'Bloggers', 'Small businesses']
  }
];

const AI_POWERED_TEMPLATES = [
  // AI Prompt Packs (5)
  {
    id: 'ai-prompts-content',
    name: 'AI Content Creation Prompt Library (100+ Prompts)',
    category: 'ai-powered',
    subcategory: 'ai-prompts',
    priceCents: 4900,
    shortDescription: '100+ tested AI prompts for content creation across all platforms.',
    fullDescription: 'Create content 10x faster with this comprehensive prompt library covering blog posts, social media, emails, and video scripts. Each prompt includes customization tips and example outputs.',
    tags: ['ai', 'prompts', 'content', 'chatgpt'],
    featured: true,
    whatsIncluded: ['100+ content prompts', 'Platform-specific sections', 'Customization guides', 'Example outputs', 'Prompt chaining techniques'],
    whoItsFor: ['Content creators', 'Marketers', 'Social media managers', 'Bloggers']
  },
  {
    id: 'ai-prompts-business',
    name: 'AI Business Strategy Prompt Library (75+ Prompts)',
    category: 'ai-powered',
    subcategory: 'ai-prompts',
    priceCents: 4900,
    shortDescription: '75+ AI prompts for business planning, strategy, and analysis.',
    fullDescription: 'Make smarter business decisions with AI-powered analysis. This library covers market research, competitor analysis, financial planning, and strategic thinking.',
    tags: ['ai', 'prompts', 'business', 'strategy'],
    featured: false,
    whatsIncluded: ['75+ business prompts', 'Strategy frameworks', 'Analysis templates', 'Decision-making prompts', 'Planning guides'],
    whoItsFor: ['Entrepreneurs', 'Business owners', 'Consultants', 'Strategists']
  },
  {
    id: 'ai-prompts-copywriting',
    name: 'AI Copywriting Prompt Library (80+ Prompts)',
    category: 'ai-powered',
    subcategory: 'ai-prompts',
    priceCents: 4900,
    shortDescription: '80+ AI prompts for high-converting copy across all channels.',
    fullDescription: 'Write copy that converts with this specialized prompt library covering headlines, sales pages, ads, and email copy. Includes proven frameworks and formulas.',
    tags: ['ai', 'prompts', 'copywriting', 'sales'],
    featured: false,
    whatsIncluded: ['80+ copywriting prompts', 'Headline formulas', 'Sales page frameworks', 'Ad copy templates', 'Email copy prompts'],
    whoItsFor: ['Copywriters', 'Marketers', 'Business owners', 'Freelancers']
  },
  {
    id: 'ai-prompts-coding',
    name: 'AI Coding Assistant Prompt Library (90+ Prompts)',
    category: 'ai-powered',
    subcategory: 'ai-prompts',
    priceCents: 4900,
    shortDescription: '90+ AI prompts for developers and no-code builders.',
    fullDescription: 'Code faster and debug smarter with this developer-focused prompt library covering code generation, debugging, documentation, and learning.',
    tags: ['ai', 'prompts', 'coding', 'developer'],
    featured: false,
    whatsIncluded: ['90+ coding prompts', 'Debug frameworks', 'Documentation templates', 'Learning prompts', 'Code review guides'],
    whoItsFor: ['Developers', 'No-code builders', 'Tech founders', 'Students']
  },
  {
    id: 'ai-prompts-research',
    name: 'AI Research & Analysis Prompt Library (75+ Prompts)',
    category: 'ai-powered',
    subcategory: 'ai-prompts',
    priceCents: 4900,
    shortDescription: '75+ AI prompts for deep research and analysis tasks.',
    fullDescription: 'Conduct thorough research with AI assistance. This library covers market research, academic research, data analysis, and synthesis.',
    tags: ['ai', 'prompts', 'research', 'analysis'],
    featured: false,
    whatsIncluded: ['75+ research prompts', 'Analysis frameworks', 'Synthesis templates', 'Fact-checking guides', 'Report structures'],
    whoItsFor: ['Researchers', 'Analysts', 'Students', 'Consultants']
  },

  // AI Workflows (5)
  {
    id: 'ai-workflow-content',
    name: 'AI Content Production Workflow System',
    category: 'ai-powered',
    subcategory: 'ai-workflows',
    priceCents: 5900,
    shortDescription: 'Complete AI-powered content production system with automation.',
    fullDescription: 'Systematize your content creation with this workflow covering ideation, creation, editing, and distribution. Includes automation triggers and quality checks.',
    tags: ['ai', 'workflow', 'content', 'automation'],
    featured: true,
    whatsIncluded: ['Workflow diagrams', 'Prompt sequences', 'Automation triggers', 'Quality checklists', 'Tool recommendations'],
    whoItsFor: ['Content teams', 'Marketing agencies', 'Solo creators', 'Media companies']
  },
  {
    id: 'ai-workflow-sales',
    name: 'AI Sales Automation Workflow System',
    category: 'ai-powered',
    subcategory: 'ai-workflows',
    priceCents: 5900,
    shortDescription: 'AI-powered sales workflow from lead to close.',
    fullDescription: 'Automate your sales process with AI. This system covers lead qualification, outreach personalization, follow-up sequences, and proposal generation.',
    tags: ['ai', 'workflow', 'sales', 'automation'],
    featured: false,
    whatsIncluded: ['Sales workflow map', 'AI qualification prompts', 'Personalization templates', 'Follow-up sequences', 'Proposal generators'],
    whoItsFor: ['Sales teams', 'SDRs', 'Account executives', 'Sales managers']
  },
  {
    id: 'ai-workflow-customer-service',
    name: 'AI Customer Service Workflow System',
    category: 'ai-powered',
    subcategory: 'ai-workflows',
    priceCents: 5900,
    shortDescription: 'AI-enhanced customer service workflow for faster resolution.',
    fullDescription: 'Improve customer satisfaction with AI-powered support. This system covers ticket triage, response generation, escalation, and feedback analysis.',
    tags: ['ai', 'workflow', 'customer-service', 'support'],
    featured: false,
    whatsIncluded: ['Support workflow map', 'Response templates', 'Escalation triggers', 'Feedback analysis', 'Knowledge base structure'],
    whoItsFor: ['Support teams', 'Customer success', 'Help desk managers', 'E-commerce brands']
  },
  {
    id: 'ai-workflow-hiring',
    name: 'AI Hiring & Recruitment Workflow System',
    category: 'ai-powered',
    subcategory: 'ai-workflows',
    priceCents: 5900,
    shortDescription: 'AI-powered hiring workflow from job post to offer.',
    fullDescription: 'Streamline hiring with AI assistance. This system covers job description writing, resume screening, interview questions, and candidate evaluation.',
    tags: ['ai', 'workflow', 'hiring', 'recruitment'],
    featured: false,
    whatsIncluded: ['Hiring workflow map', 'JD templates', 'Screening prompts', 'Interview guides', 'Evaluation frameworks'],
    whoItsFor: ['HR teams', 'Hiring managers', 'Recruiters', 'Startup founders']
  },
  {
    id: 'ai-workflow-research',
    name: 'AI Research & Analysis Workflow System',
    category: 'ai-powered',
    subcategory: 'ai-workflows',
    priceCents: 5900,
    shortDescription: 'Systematic AI research workflow for deep analysis.',
    fullDescription: 'Conduct thorough research systematically with AI. This workflow covers source gathering, analysis, synthesis, and report generation.',
    tags: ['ai', 'workflow', 'research', 'analysis'],
    featured: false,
    whatsIncluded: ['Research workflow map', 'Source evaluation', 'Analysis frameworks', 'Synthesis templates', 'Report generators'],
    whoItsFor: ['Researchers', 'Analysts', 'Consultants', 'Strategy teams']
  },

  // AI Outreach Systems (5)
  {
    id: 'ai-outreach-cold-email',
    name: 'AI Cold Email Outreach System',
    category: 'ai-powered',
    subcategory: 'ai-outreach',
    priceCents: 4900,
    shortDescription: 'AI-powered cold email system with personalization at scale.',
    fullDescription: 'Send personalized cold emails at scale with this AI system. Includes prospect research prompts, personalization frameworks, and follow-up sequences.',
    tags: ['ai', 'outreach', 'cold-email', 'sales'],
    featured: true,
    whatsIncluded: ['20 email templates', 'Personalization prompts', 'Research frameworks', 'Follow-up sequences', 'A/B testing guide'],
    whoItsFor: ['Sales teams', 'Founders', 'Business developers', 'Agency owners']
  },
  {
    id: 'ai-outreach-linkedin',
    name: 'AI LinkedIn Outreach System',
    category: 'ai-powered',
    subcategory: 'ai-outreach',
    priceCents: 4900,
    shortDescription: 'AI-powered LinkedIn outreach for B2B lead generation.',
    fullDescription: 'Generate B2B leads on LinkedIn with AI-powered personalization. Includes connection requests, message sequences, and content engagement strategies.',
    tags: ['ai', 'outreach', 'linkedin', 'b2b'],
    featured: false,
    whatsIncluded: ['15 message templates', 'Connection request scripts', 'Engagement prompts', 'Content strategy', 'Profile optimization'],
    whoItsFor: ['B2B sales', 'Consultants', 'Recruiters', 'Founders']
  },
  {
    id: 'ai-outreach-influencer',
    name: 'AI Influencer Outreach System',
    category: 'ai-powered',
    subcategory: 'ai-outreach',
    priceCents: 4900,
    shortDescription: 'AI-powered influencer outreach for brand partnerships.',
    fullDescription: 'Land influencer partnerships with AI-crafted outreach. Includes research prompts, pitch templates, negotiation frameworks, and collaboration briefs.',
    tags: ['ai', 'outreach', 'influencer', 'partnerships'],
    featured: false,
    whatsIncluded: ['15 pitch templates', 'Research prompts', 'Negotiation scripts', 'Collaboration briefs', 'Follow-up sequences'],
    whoItsFor: ['Brand managers', 'Marketing teams', 'E-commerce brands', 'PR agencies']
  },
  {
    id: 'ai-outreach-pr',
    name: 'AI PR & Media Outreach System',
    category: 'ai-powered',
    subcategory: 'ai-outreach',
    priceCents: 4900,
    shortDescription: 'AI-powered PR outreach for media coverage.',
    fullDescription: 'Get media coverage with AI-crafted pitches. Includes journalist research, pitch angles, press release templates, and follow-up strategies.',
    tags: ['ai', 'outreach', 'pr', 'media'],
    featured: false,
    whatsIncluded: ['12 pitch templates', 'Press release framework', 'Journalist research prompts', 'Angle development', 'Follow-up sequences'],
    whoItsFor: ['PR professionals', 'Founders', 'Marketing teams', 'Authors']
  },
  {
    id: 'ai-outreach-partnership',
    name: 'AI Partnership Outreach System',
    category: 'ai-powered',
    subcategory: 'ai-outreach',
    priceCents: 4900,
    shortDescription: 'AI-powered partnership outreach for strategic alliances.',
    fullDescription: 'Build strategic partnerships with AI-crafted outreach. Includes partner identification, value proposition development, and collaboration frameworks.',
    tags: ['ai', 'outreach', 'partnership', 'business-development'],
    featured: false,
    whatsIncluded: ['10 outreach templates', 'Partner research prompts', 'Value prop frameworks', 'Collaboration structures', 'Negotiation guides'],
    whoItsFor: ['Business developers', 'Founders', 'Partnership managers', 'Growth teams']
  }
];

const REAL_ESTATE_TEMPLATES = [
  // Realtor Social Packs (5)
  {
    id: 'realtor-social-luxury',
    name: 'Luxury Real Estate Social Media Pack',
    category: 'real-estate',
    subcategory: 'realtor-social',
    priceCents: 3900,
    shortDescription: '20 premium social posts for luxury real estate agents.',
    fullDescription: 'Attract high-net-worth clients with 20 sophisticated social media posts designed for luxury real estate marketing. Includes property showcases, lifestyle content, and market insights.',
    tags: ['real-estate', 'luxury', 'social-media', 'high-end'],
    featured: true,
    whatsIncluded: ['20 luxury posts', 'Property showcase templates', 'Lifestyle content', 'Market insight posts', 'Hashtag strategy'],
    whoItsFor: ['Luxury agents', 'High-end brokers', 'Luxury teams', 'Premium markets']
  },
  {
    id: 'realtor-social-first-time',
    name: 'First-Time Buyer Social Media Pack',
    category: 'real-estate',
    subcategory: 'realtor-social',
    priceCents: 3400,
    shortDescription: '20 educational social posts for first-time home buyers.',
    fullDescription: 'Attract first-time buyers with 20 educational and encouraging social posts covering the home buying process, tips, and common questions.',
    tags: ['real-estate', 'first-time-buyer', 'educational', 'social-media'],
    featured: false,
    whatsIncluded: ['20 educational posts', 'Process explainers', 'Tip content', 'FAQ posts', 'Encouragement content'],
    whoItsFor: ['Buyer agents', 'New agents', 'First-time buyer specialists', 'Residential agents']
  },
  {
    id: 'realtor-social-investment',
    name: 'Real Estate Investment Social Media Pack',
    category: 'real-estate',
    subcategory: 'realtor-social',
    priceCents: 3900,
    shortDescription: '20 investor-focused social posts for real estate agents.',
    fullDescription: 'Attract real estate investors with 20 data-driven social posts covering ROI analysis, market trends, and investment strategies.',
    tags: ['real-estate', 'investment', 'investor', 'social-media'],
    featured: false,
    whatsIncluded: ['20 investor posts', 'ROI content', 'Market analysis posts', 'Strategy content', 'Case study formats'],
    whoItsFor: ['Investment specialists', 'Commercial agents', 'Investor-focused agents', 'Property managers']
  },
  {
    id: 'realtor-social-local',
    name: 'Local Market Expert Social Media Pack',
    category: 'real-estate',
    subcategory: 'realtor-social',
    priceCents: 3400,
    shortDescription: '20 community-focused social posts to establish local expertise.',
    fullDescription: 'Become the go-to local expert with 20 community-focused posts covering neighborhood highlights, local events, and market updates.',
    tags: ['real-estate', 'local', 'community', 'social-media'],
    featured: false,
    whatsIncluded: ['20 local posts', 'Neighborhood spotlights', 'Event content', 'Market updates', 'Community features'],
    whoItsFor: ['Local agents', 'Neighborhood specialists', 'Community-focused agents', 'Farm area agents']
  },
  {
    id: 'realtor-social-seller',
    name: 'Home Seller Social Media Pack',
    category: 'real-estate',
    subcategory: 'realtor-social',
    priceCents: 3400,
    shortDescription: '20 seller-focused social posts to attract listing clients.',
    fullDescription: 'Win more listings with 20 seller-focused posts covering home prep tips, pricing strategies, and success stories.',
    tags: ['real-estate', 'seller', 'listing', 'social-media'],
    featured: false,
    whatsIncluded: ['20 seller posts', 'Home prep tips', 'Pricing content', 'Success stories', 'Market timing posts'],
    whoItsFor: ['Listing agents', 'Seller specialists', 'Experienced agents', 'Listing teams']
  },

  // Listing Descriptions (5)
  {
    id: 'listing-descriptions-luxury',
    name: 'Luxury Property Listing Descriptions (15 Templates)',
    category: 'real-estate',
    subcategory: 'listing-descriptions',
    priceCents: 2900,
    shortDescription: '15 elegant listing description templates for luxury properties.',
    fullDescription: 'Showcase luxury properties with 15 sophisticated listing description templates that highlight premium features, lifestyle benefits, and exclusive amenities.',
    tags: ['real-estate', 'listing', 'luxury', 'copywriting'],
    featured: true,
    whatsIncluded: ['15 luxury templates', 'Feature highlight formulas', 'Lifestyle language', 'Amenity descriptions', 'Call-to-action phrases'],
    whoItsFor: ['Luxury agents', 'High-end listings', 'Premium properties', 'Estate sales']
  },
  {
    id: 'listing-descriptions-starter',
    name: 'Starter Home Listing Descriptions (15 Templates)',
    category: 'real-estate',
    subcategory: 'listing-descriptions',
    priceCents: 2400,
    shortDescription: '15 appealing listing description templates for starter homes.',
    fullDescription: 'Attract first-time buyers with 15 warm and inviting listing descriptions that emphasize value, potential, and lifestyle benefits.',
    tags: ['real-estate', 'listing', 'starter-home', 'copywriting'],
    featured: false,
    whatsIncluded: ['15 starter templates', 'Value language', 'Potential highlights', 'Neighborhood features', 'Buyer-focused CTAs'],
    whoItsFor: ['Residential agents', 'First-time buyer markets', 'Affordable housing', 'Entry-level listings']
  },
  {
    id: 'listing-descriptions-condo',
    name: 'Condo & Apartment Listing Descriptions (15 Templates)',
    category: 'real-estate',
    subcategory: 'listing-descriptions',
    priceCents: 2400,
    shortDescription: '15 urban-focused listing description templates for condos.',
    fullDescription: 'Sell condos faster with 15 lifestyle-focused listing descriptions highlighting urban amenities, building features, and location benefits.',
    tags: ['real-estate', 'listing', 'condo', 'urban'],
    featured: false,
    whatsIncluded: ['15 condo templates', 'Amenity highlights', 'Location language', 'Building features', 'Urban lifestyle copy'],
    whoItsFor: ['Condo specialists', 'Urban agents', 'High-rise sales', 'Downtown markets']
  },
  {
    id: 'listing-descriptions-investment',
    name: 'Investment Property Listing Descriptions (15 Templates)',
    category: 'real-estate',
    subcategory: 'listing-descriptions',
    priceCents: 2900,
    shortDescription: '15 ROI-focused listing description templates for investors.',
    fullDescription: 'Attract investors with 15 data-driven listing descriptions highlighting rental potential, cap rates, and investment benefits.',
    tags: ['real-estate', 'listing', 'investment', 'rental'],
    featured: false,
    whatsIncluded: ['15 investment templates', 'ROI language', 'Rental potential', 'Cap rate highlights', 'Investor CTAs'],
    whoItsFor: ['Investment specialists', 'Multi-family agents', 'Commercial agents', 'Rental property sales']
  },
  {
    id: 'listing-descriptions-land',
    name: 'Land & Lot Listing Descriptions (15 Templates)',
    category: 'real-estate',
    subcategory: 'listing-descriptions',
    priceCents: 2400,
    shortDescription: '15 vision-inspiring listing description templates for land.',
    fullDescription: 'Sell land and lots with 15 vision-focused listing descriptions that help buyers imagine possibilities and understand value.',
    tags: ['real-estate', 'listing', 'land', 'development'],
    featured: false,
    whatsIncluded: ['15 land templates', 'Vision language', 'Development potential', 'Location benefits', 'Zoning highlights'],
    whoItsFor: ['Land specialists', 'Development sales', 'Rural agents', 'Lot sales']
  },

  // Buyer/Seller Guides (5)
  {
    id: 'guide-first-time-buyer',
    name: 'First-Time Home Buyer Guide (10 Pages)',
    category: 'real-estate',
    subcategory: 'buyer-guides',
    priceCents: 3400,
    shortDescription: 'Comprehensive 10-page guide for first-time home buyers.',
    fullDescription: 'Help first-time buyers navigate the process with this detailed guide covering financing, searching, offers, inspections, and closing.',
    tags: ['real-estate', 'buyer', 'guide', 'first-time'],
    featured: true,
    whatsIncluded: ['10-page guide', 'Process timeline', 'Checklist templates', 'Budget worksheets', 'FAQ section'],
    whoItsFor: ['Buyer agents', 'First-time buyer specialists', 'Real estate teams', 'Brokerages']
  },
  {
    id: 'guide-home-seller',
    name: 'Home Seller Success Guide (10 Pages)',
    category: 'real-estate',
    subcategory: 'seller-guides',
    priceCents: 3400,
    shortDescription: 'Complete 10-page guide for home sellers.',
    fullDescription: 'Prepare sellers for success with this comprehensive guide covering pricing, staging, marketing, showings, and negotiations.',
    tags: ['real-estate', 'seller', 'guide', 'listing'],
    featured: false,
    whatsIncluded: ['10-page guide', 'Pricing strategy', 'Staging checklist', 'Marketing overview', 'Timeline template'],
    whoItsFor: ['Listing agents', 'Seller specialists', 'Real estate teams', 'Brokerages']
  },
  {
    id: 'guide-investment-buyer',
    name: 'Real Estate Investment Buyer Guide (8 Pages)',
    category: 'real-estate',
    subcategory: 'buyer-guides',
    priceCents: 3900,
    shortDescription: 'Strategic 8-page guide for real estate investors.',
    fullDescription: 'Educate investor clients with this strategic guide covering analysis methods, financing options, and investment strategies.',
    tags: ['real-estate', 'investor', 'guide', 'analysis'],
    featured: false,
    whatsIncluded: ['8-page guide', 'ROI calculators', 'Analysis frameworks', 'Financing options', 'Strategy overview'],
    whoItsFor: ['Investment specialists', 'Commercial agents', 'Investor-focused teams', 'Property managers']
  },
  {
    id: 'guide-relocation',
    name: 'Relocation Buyer Guide (8 Pages)',
    category: 'real-estate',
    subcategory: 'buyer-guides',
    priceCents: 3400,
    shortDescription: 'Helpful 8-page guide for relocating buyers.',
    fullDescription: 'Support relocating clients with this comprehensive guide covering area research, remote buying process, and settling in.',
    tags: ['real-estate', 'relocation', 'guide', 'moving'],
    featured: false,
    whatsIncluded: ['8-page guide', 'Area research template', 'Remote process tips', 'Moving checklist', 'Local resources'],
    whoItsFor: ['Relocation specialists', 'Buyer agents', 'Corporate relocation', 'Military relocation']
  },
  {
    id: 'guide-downsizing',
    name: 'Downsizing & Senior Seller Guide (8 Pages)',
    category: 'real-estate',
    subcategory: 'seller-guides',
    priceCents: 3400,
    shortDescription: 'Compassionate 8-page guide for downsizing sellers.',
    fullDescription: 'Support downsizing clients with this thoughtful guide covering decluttering, emotional preparation, and transition planning.',
    tags: ['real-estate', 'downsizing', 'senior', 'guide'],
    featured: false,
    whatsIncluded: ['8-page guide', 'Decluttering plan', 'Emotional support tips', 'Transition timeline', 'Resource list'],
    whoItsFor: ['Senior specialists', 'Downsizing agents', 'Estate sales', 'Transition specialists']
  }
];

const ECOMMERCE_TEMPLATES = [
  // Product Descriptions (5)
  {
    id: 'product-descriptions-fashion',
    name: 'Fashion Product Description Pack (20 Templates)',
    category: 'ecommerce',
    subcategory: 'product-descriptions',
    priceCents: 2900,
    shortDescription: '20 stylish product description templates for fashion brands.',
    fullDescription: 'Sell more fashion with 20 compelling product descriptions covering clothing, accessories, and footwear. Each template highlights style, fit, and lifestyle benefits.',
    tags: ['ecommerce', 'fashion', 'product', 'copywriting'],
    featured: true,
    whatsIncluded: ['20 fashion templates', 'Style language', 'Fit descriptions', 'Material highlights', 'Lifestyle copy'],
    whoItsFor: ['Fashion brands', 'Clothing stores', 'Boutiques', 'Accessory sellers']
  },
  {
    id: 'product-descriptions-beauty',
    name: 'Beauty Product Description Pack (20 Templates)',
    category: 'ecommerce',
    subcategory: 'product-descriptions',
    priceCents: 2900,
    shortDescription: '20 luxurious product description templates for beauty brands.',
    fullDescription: 'Elevate your beauty products with 20 sensory-rich descriptions covering skincare, makeup, and haircare. Each template emphasizes benefits, ingredients, and results.',
    tags: ['ecommerce', 'beauty', 'skincare', 'copywriting'],
    featured: false,
    whatsIncluded: ['20 beauty templates', 'Benefit language', 'Ingredient highlights', 'Results copy', 'Sensory descriptions'],
    whoItsFor: ['Beauty brands', 'Skincare companies', 'Cosmetics sellers', 'Hair care brands']
  },
  {
    id: 'product-descriptions-tech',
    name: 'Tech Product Description Pack (20 Templates)',
    category: 'ecommerce',
    subcategory: 'product-descriptions',
    priceCents: 2900,
    shortDescription: '20 feature-rich product description templates for tech products.',
    fullDescription: 'Sell tech products effectively with 20 clear, benefit-focused descriptions covering gadgets, electronics, and accessories.',
    tags: ['ecommerce', 'tech', 'electronics', 'copywriting'],
    featured: false,
    whatsIncluded: ['20 tech templates', 'Feature highlights', 'Spec formatting', 'Benefit translation', 'Comparison language'],
    whoItsFor: ['Tech sellers', 'Electronics stores', 'Gadget brands', 'Accessory sellers']
  },
  {
    id: 'product-descriptions-home',
    name: 'Home & Living Product Description Pack (20 Templates)',
    category: 'ecommerce',
    subcategory: 'product-descriptions',
    priceCents: 2900,
    shortDescription: '20 lifestyle-focused product descriptions for home goods.',
    fullDescription: 'Transform houses into homes with 20 evocative product descriptions for furniture, decor, and home accessories.',
    tags: ['ecommerce', 'home', 'furniture', 'decor'],
    featured: false,
    whatsIncluded: ['20 home templates', 'Lifestyle language', 'Quality highlights', 'Space descriptions', 'Style copy'],
    whoItsFor: ['Home goods brands', 'Furniture sellers', 'Decor shops', 'Lifestyle brands']
  },
  {
    id: 'product-descriptions-food',
    name: 'Food & Beverage Product Description Pack (20 Templates)',
    category: 'ecommerce',
    subcategory: 'product-descriptions',
    priceCents: 2900,
    shortDescription: '20 mouth-watering product descriptions for food brands.',
    fullDescription: 'Make taste buds tingle with 20 sensory-rich product descriptions for food, beverages, and specialty items.',
    tags: ['ecommerce', 'food', 'beverage', 'gourmet'],
    featured: false,
    whatsIncluded: ['20 food templates', 'Sensory language', 'Origin stories', 'Pairing suggestions', 'Quality highlights'],
    whoItsFor: ['Food brands', 'Beverage companies', 'Gourmet sellers', 'Specialty food shops']
  },

  // Shopify/E-commerce Flows (5)
  {
    id: 'shopify-email-flows',
    name: 'Shopify Email Flow Bundle (5 Flows)',
    category: 'ecommerce',
    subcategory: 'shopify-banners',
    priceCents: 4900,
    shortDescription: '5 essential email flows for Shopify stores.',
    fullDescription: 'Automate your Shopify email marketing with 5 essential flows: welcome, abandoned cart, post-purchase, win-back, and browse abandonment.',
    tags: ['shopify', 'email', 'automation', 'flows'],
    featured: true,
    whatsIncluded: ['5 complete flows', 'Email templates', 'Timing recommendations', 'Subject lines', 'Segmentation tips'],
    whoItsFor: ['Shopify stores', 'E-commerce brands', 'DTC companies', 'Online retailers']
  },
  {
    id: 'shopify-homepage-sections',
    name: 'Shopify Homepage Section Templates',
    category: 'ecommerce',
    subcategory: 'shopify-banners',
    priceCents: 3400,
    shortDescription: 'High-converting homepage section copy templates.',
    fullDescription: 'Optimize your Shopify homepage with copy templates for hero sections, featured products, testimonials, and trust badges.',
    tags: ['shopify', 'homepage', 'copy', 'conversion'],
    featured: false,
    whatsIncluded: ['Hero section templates', 'Product feature copy', 'Testimonial formats', 'Trust badge copy', 'CTA variations'],
    whoItsFor: ['Shopify stores', 'E-commerce brands', 'Store designers', 'Conversion optimizers']
  },
  {
    id: 'ecommerce-upsell-templates',
    name: 'E-Commerce Upsell & Cross-Sell Templates',
    category: 'ecommerce',
    subcategory: 'upsell-flows',
    priceCents: 3400,
    shortDescription: 'Increase AOV with upsell and cross-sell templates.',
    fullDescription: 'Boost average order value with proven upsell and cross-sell copy templates for product pages, cart, and checkout.',
    tags: ['ecommerce', 'upsell', 'cross-sell', 'aov'],
    featured: false,
    whatsIncluded: ['Product page upsells', 'Cart upsells', 'Checkout offers', 'Bundle copy', 'Urgency templates'],
    whoItsFor: ['E-commerce stores', 'Shopify sellers', 'DTC brands', 'Online retailers']
  },
  {
    id: 'ecommerce-sms-templates',
    name: 'E-Commerce SMS Marketing Templates',
    category: 'ecommerce',
    subcategory: 'shopify-banners',
    priceCents: 2900,
    shortDescription: '25 high-converting SMS templates for e-commerce.',
    fullDescription: 'Drive sales with SMS marketing using 25 proven templates covering promotions, abandoned carts, shipping updates, and VIP offers.',
    tags: ['ecommerce', 'sms', 'marketing', 'mobile'],
    featured: false,
    whatsIncluded: ['25 SMS templates', 'Promo messages', 'Cart recovery', 'Shipping updates', 'VIP offers'],
    whoItsFor: ['E-commerce brands', 'Shopify stores', 'DTC companies', 'Mobile marketers']
  },
  {
    id: 'influencer-outreach-ecommerce',
    name: 'E-Commerce Influencer Outreach Kit',
    category: 'ecommerce',
    subcategory: 'influencer-outreach',
    priceCents: 3900,
    shortDescription: 'Complete influencer outreach kit for product brands.',
    fullDescription: 'Land influencer partnerships with this comprehensive kit including outreach templates, collaboration briefs, and contract frameworks.',
    tags: ['ecommerce', 'influencer', 'outreach', 'partnerships'],
    featured: false,
    whatsIncluded: ['15 outreach templates', 'Collaboration briefs', 'Contract templates', 'Negotiation scripts', 'Tracking spreadsheet'],
    whoItsFor: ['E-commerce brands', 'Product companies', 'Marketing teams', 'Brand managers']
  }
];

const PRODUCTIVITY_TEMPLATES = [
  // Planners (5)
  {
    id: 'planner-annual-goals',
    name: 'Annual Goal Planning System (20 Pages)',
    category: 'productivity',
    subcategory: 'planners',
    priceCents: 3400,
    shortDescription: '20-page annual planning system for goal achievers.',
    fullDescription: 'Plan your best year with this comprehensive 20-page system covering vision setting, goal breakdown, quarterly planning, and monthly reviews.',
    tags: ['planner', 'goals', 'annual', 'productivity'],
    featured: true,
    whatsIncluded: ['20-page planner', 'Vision worksheets', 'Goal breakdown templates', 'Quarterly reviews', 'Monthly check-ins'],
    whoItsFor: ['Goal setters', 'Entrepreneurs', 'Professionals', 'Personal development enthusiasts']
  },
  {
    id: 'planner-business-quarterly',
    name: 'Business Quarterly Planner (15 Pages)',
    category: 'productivity',
    subcategory: 'planners',
    priceCents: 2900,
    shortDescription: '15-page quarterly business planning system.',
    fullDescription: 'Plan your business quarter strategically with this 15-page system covering OKRs, project planning, and performance tracking.',
    tags: ['planner', 'business', 'quarterly', 'okr'],
    featured: false,
    whatsIncluded: ['15-page planner', 'OKR templates', 'Project trackers', 'KPI dashboards', 'Review frameworks'],
    whoItsFor: ['Business owners', 'Team leaders', 'Managers', 'Entrepreneurs']
  },
  {
    id: 'planner-content-creator',
    name: 'Content Creator Planner (18 Pages)',
    category: 'productivity',
    subcategory: 'planners',
    priceCents: 2900,
    shortDescription: '18-page planner designed for content creators.',
    fullDescription: 'Organize your content creation with this 18-page planner covering content calendars, batch planning, analytics tracking, and monetization goals.',
    tags: ['planner', 'content', 'creator', 'social-media'],
    featured: false,
    whatsIncluded: ['18-page planner', 'Content calendars', 'Batch planning sheets', 'Analytics trackers', 'Revenue goals'],
    whoItsFor: ['Content creators', 'YouTubers', 'Podcasters', 'Bloggers']
  },
  {
    id: 'planner-project-manager',
    name: 'Project Manager Planner (15 Pages)',
    category: 'productivity',
    subcategory: 'planners',
    priceCents: 2900,
    shortDescription: '15-page planner for project management professionals.',
    fullDescription: 'Manage projects effectively with this 15-page planner covering project timelines, resource allocation, risk management, and stakeholder communication.',
    tags: ['planner', 'project', 'management', 'professional'],
    featured: false,
    whatsIncluded: ['15-page planner', 'Timeline templates', 'Resource trackers', 'Risk registers', 'Communication logs'],
    whoItsFor: ['Project managers', 'Team leads', 'Operations managers', 'Coordinators']
  },
  {
    id: 'planner-wellness-lifestyle',
    name: 'Wellness & Lifestyle Planner (20 Pages)',
    category: 'productivity',
    subcategory: 'planners',
    priceCents: 2900,
    shortDescription: '20-page holistic wellness and lifestyle planner.',
    fullDescription: 'Balance your life with this 20-page wellness planner covering fitness goals, nutrition tracking, self-care routines, and mindfulness practices.',
    tags: ['planner', 'wellness', 'lifestyle', 'health'],
    featured: false,
    whatsIncluded: ['20-page planner', 'Fitness trackers', 'Meal planners', 'Self-care schedules', 'Gratitude journals'],
    whoItsFor: ['Health enthusiasts', 'Wellness seekers', 'Busy professionals', 'Self-improvement focused']
  },

  // Trackers (5)
  {
    id: 'tracker-habit-90day',
    name: '90-Day Habit Tracker System (12 Pages)',
    category: 'productivity',
    subcategory: 'habit-trackers',
    priceCents: 2400,
    shortDescription: '12-page habit tracking system for lasting change.',
    fullDescription: 'Build lasting habits with this 90-day tracking system covering habit stacking, streak tracking, and reflection prompts.',
    tags: ['tracker', 'habits', '90-day', 'behavior'],
    featured: true,
    whatsIncluded: ['12-page tracker', 'Habit stacking guide', 'Daily tracking sheets', 'Weekly reviews', 'Milestone celebrations'],
    whoItsFor: ['Habit builders', 'Self-improvers', 'Goal setters', 'Personal development enthusiasts']
  },
  {
    id: 'tracker-budget-monthly',
    name: 'Monthly Budget Tracker (15 Pages)',
    category: 'productivity',
    subcategory: 'budget-trackers',
    priceCents: 2400,
    shortDescription: '15-page monthly budget tracking system.',
    fullDescription: 'Take control of your finances with this 15-page budget tracker covering income, expenses, savings goals, and spending analysis.',
    tags: ['tracker', 'budget', 'finance', 'money'],
    featured: false,
    whatsIncluded: ['15-page tracker', 'Income tracking', 'Expense categories', 'Savings goals', 'Spending analysis'],
    whoItsFor: ['Budget conscious', 'Savers', 'Financial planners', 'Debt reducers']
  },
  {
    id: 'tracker-content-analytics',
    name: 'Content Analytics Tracker (10 Pages)',
    category: 'productivity',
    subcategory: 'content-planners',
    priceCents: 2400,
    shortDescription: '10-page content performance tracking system.',
    fullDescription: 'Track your content performance with this 10-page analytics tracker covering engagement metrics, growth trends, and content optimization.',
    tags: ['tracker', 'content', 'analytics', 'performance'],
    featured: false,
    whatsIncluded: ['10-page tracker', 'Platform metrics', 'Growth charts', 'Content scores', 'Optimization notes'],
    whoItsFor: ['Content creators', 'Social media managers', 'Marketers', 'Influencers']
  },
  {
    id: 'tracker-fitness-workout',
    name: 'Fitness & Workout Tracker (12 Pages)',
    category: 'productivity',
    subcategory: 'habit-trackers',
    priceCents: 2400,
    shortDescription: '12-page fitness and workout tracking system.',
    fullDescription: 'Crush your fitness goals with this 12-page tracker covering workout logs, progress photos, measurements, and personal records.',
    tags: ['tracker', 'fitness', 'workout', 'health'],
    featured: false,
    whatsIncluded: ['12-page tracker', 'Workout logs', 'Progress tracking', 'Measurement charts', 'PR records'],
    whoItsFor: ['Fitness enthusiasts', 'Gym goers', 'Athletes', 'Health focused']
  },
  {
    id: 'tracker-reading-learning',
    name: 'Reading & Learning Tracker (10 Pages)',
    category: 'productivity',
    subcategory: 'habit-trackers',
    priceCents: 2400,
    shortDescription: '10-page reading and learning tracking system.',
    fullDescription: 'Track your learning journey with this 10-page system covering book logs, course progress, key takeaways, and implementation plans.',
    tags: ['tracker', 'reading', 'learning', 'books'],
    featured: false,
    whatsIncluded: ['10-page tracker', 'Book logs', 'Course trackers', 'Takeaway notes', 'Implementation plans'],
    whoItsFor: ['Readers', 'Lifelong learners', 'Students', 'Knowledge seekers']
  }
];

const PROFESSIONAL_DOCS_TEMPLATES = [
  // Resumes (3)
  {
    id: 'resume-modern-professional',
    name: 'Modern Professional Resume Template',
    category: 'professional-docs',
    subcategory: 'resumes',
    priceCents: 2400,
    shortDescription: 'Clean, ATS-friendly resume template for professionals.',
    fullDescription: 'Land more interviews with this modern, ATS-optimized resume template. Includes formatting guidelines, action verb lists, and customization tips.',
    tags: ['resume', 'professional', 'ats', 'job-search'],
    featured: true,
    whatsIncluded: ['Resume template', 'ATS optimization guide', 'Action verb list', 'Formatting tips', 'Cover letter template'],
    whoItsFor: ['Job seekers', 'Career changers', 'Professionals', 'Recent graduates']
  },
  {
    id: 'resume-executive',
    name: 'Executive Resume Template',
    category: 'professional-docs',
    subcategory: 'resumes',
    priceCents: 2900,
    shortDescription: 'Premium executive resume template for senior leaders.',
    fullDescription: 'Position yourself for executive roles with this premium resume template designed for C-suite, VP, and director-level positions.',
    tags: ['resume', 'executive', 'leadership', 'c-suite'],
    featured: false,
    whatsIncluded: ['Executive template', 'Leadership language', 'Achievement frameworks', 'Board bio template', 'LinkedIn optimization'],
    whoItsFor: ['Executives', 'Senior leaders', 'Directors', 'VPs']
  },
  {
    id: 'resume-creative',
    name: 'Creative Professional Resume Template',
    category: 'professional-docs',
    subcategory: 'resumes',
    priceCents: 2400,
    shortDescription: 'Visually striking resume template for creative professionals.',
    fullDescription: 'Stand out in creative industries with this visually appealing resume template that balances creativity with professionalism.',
    tags: ['resume', 'creative', 'design', 'portfolio'],
    featured: false,
    whatsIncluded: ['Creative template', 'Portfolio integration', 'Visual hierarchy guide', 'Project showcase', 'Digital version tips'],
    whoItsFor: ['Designers', 'Marketers', 'Writers', 'Creative professionals']
  },

  // Pitch Decks (2)
  {
    id: 'pitch-deck-startup',
    name: 'Startup Pitch Deck Template (12 Slides)',
    category: 'professional-docs',
    subcategory: 'pitch-decks',
    priceCents: 4900,
    shortDescription: '12-slide investor pitch deck template for startups.',
    fullDescription: 'Raise funding with this proven 12-slide pitch deck template covering problem, solution, market, traction, team, and ask.',
    tags: ['pitch-deck', 'startup', 'investor', 'funding'],
    featured: true,
    whatsIncluded: ['12-slide template', 'Slide-by-slide guide', 'Design tips', 'Storytelling framework', 'Appendix templates'],
    whoItsFor: ['Startup founders', 'Entrepreneurs', 'Seeking funding', 'Pitch competitions']
  },
  {
    id: 'pitch-deck-sales',
    name: 'Sales Pitch Deck Template (10 Slides)',
    category: 'professional-docs',
    subcategory: 'pitch-decks',
    priceCents: 3900,
    shortDescription: '10-slide sales pitch deck for B2B presentations.',
    fullDescription: 'Close more deals with this persuasive 10-slide sales deck template covering pain points, solution, proof, and next steps.',
    tags: ['pitch-deck', 'sales', 'b2b', 'presentation'],
    featured: false,
    whatsIncluded: ['10-slide template', 'Sales narrative guide', 'Objection handling', 'Case study format', 'Proposal template'],
    whoItsFor: ['Sales teams', 'Account executives', 'Business developers', 'Consultants']
  }
];

// Export all template specs
module.exports = {
  SOCIAL_MEDIA_TEMPLATES,
  BUSINESS_MARKETING_TEMPLATES,
  AI_POWERED_TEMPLATES,
  REAL_ESTATE_TEMPLATES,
  ECOMMERCE_TEMPLATES,
  PRODUCTIVITY_TEMPLATES,
  PROFESSIONAL_DOCS_TEMPLATES,
  ALL_TEMPLATES: [
    ...SOCIAL_MEDIA_TEMPLATES,
    ...BUSINESS_MARKETING_TEMPLATES,
    ...AI_POWERED_TEMPLATES,
    ...REAL_ESTATE_TEMPLATES,
    ...ECOMMERCE_TEMPLATES,
    ...PRODUCTIVITY_TEMPLATES,
    ...PROFESSIONAL_DOCS_TEMPLATES
  ]
};
